[package]
name = "muni_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.22", features = [ "macros", "rt-multi-thread" ] }
rocket = "0.5.0-rc.2"
twitch-irc = { version = "5.0", features = [ "refreshing-token-native-tls" ] }
twitch_oauth2 = "0.9"
async-trait = "0.1"
serde_json = "1.0"
open = "3"
reqwest = "0.11"
serde = "1"
regex = "1"
lazy_static = "1.4"
rand = "0.8"
sled = "0.34"
