[package]
name = "muni_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
chrono = "0.4.23"
clap = "4.4.6"
diesel = { version = "2.0.0", features = ["postgres"] }
dotenvy = "0.15"
once_cell = "1.18.0"
open = "3"
poise = "0.5.5"
rand = { version = "0.8", features = ["std_rng"] }
regex = "1"
reqwest = "0.11"
rocket = "0.5.0-rc.2"
serde = "1"
serde_json = "1.0"
tokio = { version = "1.22", features = [ "full" ] }
twitch-irc = { version = "5.0", features = [ "refreshing-token-native-tls" ] }
twitch_oauth2 = "0.9"
