[package]
name = "muni_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.22", features = [ "macros", "rt-multi-thread" ] }
futures = "0.3"
rocket = "0.4"
twitch-irc = { version = "5.0", features = [ "refreshing-token-native-tls" ] }
async-trait = "0.1"
serde_json = "1.0.89"
